Feat: reusable button component added
lightning-campaigns/lnGiveaway-frontend pull request #11
Opened 2023-03-05 11:01 UTC by DaScOrPiO

2023-03-05 12:31 UTC, Extheoisah requested changes

2023-03-05 12:31 UTC, Extheoisah commented on .eslintrc.json
> +        "endOfLine": "true"
The check code test is failing because of this line and some prettier errors.
```suggestion
        "endOfLine": "lf"
```

2023-03-05 12:31 UTC, Extheoisah commented on src/components/buttons/button.tsx
> +interface PropTypes {
It's better to rename this to `ButtonProps` than proptypes. Proptypes convey a different meaning in my opinion 
```suggestion
interface ButtonTypes {
```

2023-03-05 13:12 UTC, DaScOrPiO commented on .eslintrc.json
> +        "endOfLine": "true"
The Eslint in my environment throws error due to this line before the update and I'm not able to code.

2023-03-05 13:12 UTC, DaScOrPiO commented
Noted

2023-03-08 20:53 UTC, Extheoisah approved these changes

2023-03-08 20:53 UTC, merged